option(OPTION_OMP "Build with OpenMP support" ON)
option(VERBOSE "Build in verbose mode" OFF)
option(PICKY_DEVELOPER "Build with picky developer flags" OFF)
option(BUILD_SHARED_LIBS "Build shared libraries" ON)
option(OPTION_SMID "Build with SMID (if avilable)" ON)
option(OPTION_SSE2 "Build with SSE2 (if avilable)" ON)
